export const ACTION_TYPES = {
   INPUT_CHANGE: 'INPUT_CHANGE',
   SET_DIET: 'SET_DIET',
   REMOVE_DIET: 'REMOVE_DIET',
   SET_EXTENDED_INGREDIENT: 'SET_EXTENDED_INGREDIENT',
   REMOVE_EXTENDED_INGREDIENT: 'REMOVE_EXTENDED_INGREDIENT',
   SET_INSTRUCTIONS_NAME: 'SET_INSTRUCTION_NAME',
   ADD_STEP: 'ADD_STEP',
   REMOVE_STEP: 'REMOVE_STEP',
};
