export const actionTypes = {
   RECIPES_FETCH_START: 'RECIPES_FETCH_START',
   RECIPES_FETCH_SUCCESS: 'RECIPES_FETCH_SUCCESS',
   RECIPES_FETCH_ERROR: 'RECIPES_FETCH_ERROR',
   RECIPES_ADD_START: 'RECIPES_ADD_START',
   SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
   SET_VISIBILITY_ORDER: 'SET_VISIBILITY_ORDER',
};