export const actionTypes = {
   FETCH_START: 'FETCH_START',
   FETCH_SUCCESS: 'FETCH_SUCCESS',
   FETCH_ERROR: 'FETCH_ERROR',
   ADD_RECIPE: 'ADD_RECIPE',
   REMOVE_RECIPE: 'REMOVE_RECIPE',
   SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
   SET_DIET_FILTER: 'SET_DIET_FILTER',
   SET_SOURCE_FILTER: 'SET_SOURCE_FILTER',
   SET_VISIBILITY_ORDER: 'SET_VISIBILITY_ORDER',
   RESET_FORM: 'RESET_FORM',
};

export const orderTypes = {
   TITLE_ASC: 'TITLE_ASC',
   TITLE_DESC: 'TITLE_DESC',
   HEALTH_SCORE_ASC: 'HEALTH_SCORE_ASC',
   HEALTH_SCORE_DESC: 'HEALTH_SCORE_DESC',
};