export const actionTypes = {
   FETCH_START: 'FETCH_START',
   FETCH_SUCCESS: 'FETCH_SUCCESS',
   FETCH_ERROR: 'FETCH_ERROR',
   RECIPES_ADD_START: 'RECIPES_ADD_START',
   SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
   SET_VISIBILITY_ORDER: 'SET_VISIBILITY_ORDER',
   RESET_FORM: 'RESET_FORM',
};